global:
  scrape_interval: 45s # Slow scrape to save CPU on t3.micro

rule_files:
  - '/etc/prometheus/alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'airflow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['airflow-webserver:8080']        
